import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Fira_Sans} from "next/font/google";
//import DropDown from "@/components/Dropdown";
import SubjectDropdown from "@/components/SubjectDropdown";
import TimeDropdown from "@/components/TimeDropdown";
import LocationDropdown from "@/components/LocationDropdown";

const fira_Sans = Fira_Sans({
  subsets: ["latin"],
  weight: ["400","300","700"],
  style: ["normal","italic"]

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fira_Sans.className} antialiased`}>
        <Navbar />
        <main>
            {children}
        </main>
        <SubjectDropdown />
        <TimeDropdown />
        <LocationDropdown />
      </body>
    </html>
  );
}
