import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Fira_Sans } from "next/font/google";
import SidebarTable from "@/components/SidebarTable";
interface ClassInformation {
  Class: string;
  Time: string
}
// ✅ Font setup
const fira_Sans = Fira_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
});

// ✅ Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Layout
export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${fira_Sans.className} antialiased`}>
      {/* Navbar stays at the top */}
      <Navbar />

      {/* Sidebar and content side by side */}
      <div className="flex">
        <Sidebar>
            <p>Current Classes</p>
          <SidebarTable
              data={[
              { Class: "1550 Math", Time: "9:00AM–10:20AM", Days: "M W F" },
              { Class: "2001 Comm.", Time: "1:30PM–2:50PM", Days: "T TH" },
              { Class: "1253 CS", Time: "11:00AM–12:15PM", Days: "M W" },
              { Class: "2733 Physics", Time: "3:00PM–4:20PM", Days: "T TH" },
              { Class: "2060 Math", Time: "12:30PM–1:20PM", Days: "M W F" },
          ]}
              />

          <p className="pt-5">Up Coming Tutoring Sessions</p>
            <SidebarTable data={[
                {Time: "9:30am", Location: "Patrick F Taylor Hall"},
                {Time: "10:00pm", Location: "LSU Main Library"}
            ]}/>

        </Sidebar>

        {/* Main content area */}
        <main className="flex-1 p-6">{children}</main>
      </div>
      </body>
      </html>
  );
}
